name: Deploy as Google function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on merge to main branch
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy-cloud-function.yaml@main
    with:
      app_name: cloud-logging
      entry_point: Logging
      environment: prod
      go-version: 1.21.4
      max_instances: 1
      memory: 256
      region: europe-west1
      runtime: go121
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_CLOUD_FUNCTIONS_SA_KEY: ${{ secrets.DIGDIR_CLOUD_FUNCTIONS_SA_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
